# This file is part of JavaSMT,
# an API wrapper for a collection of SMT solvers:
# https://github.com/sosy-lab/java-smt
#
# SPDX-FileCopyrightText: 2020 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

dist: focal
language: java
jdk:
  - openjdk11 # Java 11 is sufficient, larger tests are executed in Gitlab-CI
env:
  global:
    - GH_REF: github.com/sosy-lab/java-smt.git
install:
  - ant resolve-dependencies
matrix:
  include:
    - env: NAME='Build with ECJ'
      script:
        - ant build-project-ecj
    - env: NAME='Unit Tests'
      script:
        - ant unit-tests
    - env: NAME='Create Javadoc'
      script:
        - ant javadoc collect-options
    - env: NAME=Checkstyle
      script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
    - env: NAME=SpotBugs
      script:
        - ant run-spotbugs -Dspotbugs.output=text && cat SpotBugs.xml && test \! -s SpotBugs.xml
    - env: NAME='Check source-code format'
      script:
        - ant format-source && git diff --exit-code
notifications:
  email:
  - java-smt-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
