language: java
env:
  global:
  - GH_REF: github.com/dbeyer/java-smt.git
install:
  - ant resolve-dependencies
script:
  - ant unit-tests
  - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
  - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
  - ant javadoc
deploy:
  skip_cleanup: true
  provider: script
  script: build/deploy-gh-pages.sh
notifications:
  email:
  - java-smt-dev@googlegroups.com
cache:
  directories:
  - $HOME/.ivy2
