language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
      - jq
env:
  global:
    - GH_REF: github.com/sosy-lab/java-smt.git
before_install: # lets update the very old version of ANT in TravisCI
  - wget --no-check-certificate https://www.apache.org/dist/ant/binaries/apache-ant-1.10.5-bin.tar.bz2
  - tar -xvf apache-ant-1.10.5-bin.tar.bz2
  - export PATH=`pwd`/apache-ant-1.10.5/bin:$PATH
  - echo $(ant -version)
install:
  - ant resolve-dependencies
matrix:
  include:
    - env: NAME='Build with ECJ'
      script:
        - ant build-project-ecj
    - env: NAME='Unit Tests'
      script:
        - ant unit-tests-coverage
    - env: NAME='Create Javadoc'
      script:
        - ant javadoc collect-options
    - env: NAME=Checkstyle
      script:
        - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
    - env: NAME=SpotBugs
      script:
        - ant run-spotbugs -Dspotbugs.output=text && cat SpotBugs.xml && test \! -s SpotBugs.xml
    - env: NAME='Check source-code format'
      script:
        - ant format-source && git diff --exit-code
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
    on:
      condition: $NAME = "Create Javadoc"
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
    on:
      condition: $NAME = "Unit Tests"
notifications:
  email:
  - java-smt-dev@googlegroups.com
git:
  depth: 1
cache:
  directories:
  - $HOME/.ivy2
