language: java
# Only for newer ant, containers on Travis only have ant 1.8.2 which fails
sudo: required
dist: trusty
jdk:
  - oraclejdk8
env:
  global:
  - GH_REF: github.com/dbeyer/java-smt.git
install:
  - ant resolve-dependencies -Divy.repo.url=http://www.sosy-lab.org/ivy
script:
  - ant build-project-ecj
  - ant clean unit-tests-coverage
  - ant run-findbugs -Dfindbugs.output=text && cat FindBugs.xml && test \! -s FindBugs.xml
  - ant run-checkstyle -Dcheckstyle.output=plain && cat Checkstyle*.xml && [ $(cat Checkstyle*.xml | grep -vic audit) -eq 0 ]
  - ant javadoc
  - ant format-source && git diff -s --exit-code
deploy:
  - skip_cleanup: true
    provider: script
    script: build/deploy-gh-pages.sh
  - skip_cleanup: true
    provider: script
    script: build/deploy-coverage.sh
notifications:
  email:
  - java-smt-dev@googlegroups.com
cache:
  directories:
  - $HOME/.ivy2
